### ISSUE TITLE
Add Time-Locked Settings for DNS and Internet Filters

### ISSUE THREAD

**Issue by dharmiksoni** [Safe-Surfer/Core#1]
This feature would introduce the ability for users to **lock their DNS and internet filter settings** for a specified period of time. The lock would prevent any modifications or removal of existing blocked websites during the locked period. Users could still add new blocked websites, but they would not be able to disable, remove, or alter existing settings until the lock expires.

#### Lock Period Options:
- Users can select from predefined time intervals such as **1 day**, **1 week**, **1 month**, or choose a **custom date** to lock the settings.

#### Restrictions During Lock:
- Once the lock is enabled, users can no longer modify or remove existing blocked sites.
- The ability to add new blocked sites will remain, ensuring the user can enhance their protection, but they cannot undo the existing restrictions.

#### Clear Visual Indicators:
- A clear indicator on the UI showing that the settings are locked and when the lock will expire.
- A countdown timer for the remaining lock period to give users awareness of when they can modify settings again.

#### Permanent Lock Until Expiry:
- The lock can only be disabled or modified after the set time period has elapsed, providing users with a safeguard against impulsively disabling their filters.

**Comment by kirwan-safesurfer** [comment]
We've added this request into our private Issues system.
